### ISSUE TITLE
Unmarshalling error when using NRQL with FACET clause

### ISSUE THREAD

**Issue by sirianni** [newrelic/newrelic-cli#1500]
### Description
`nrql query` returns an unmarshalling error when used with `FACET` clause.

### Current behavior
```
newrelic nrql query -q 'SELECT latest(k8s.pod.memory.usage) FROM Metric FACET `k8s.pod.name` SINCE 3 MINUTES AGO TIMESERIES 1 MINUTE'
cannot unmarshal array into Go struct field NRDBResultContainer.data.Actor.Account.NRQL.otherResult of type nrdb.NRDBResult
```

### Expected behavior
I expect the query to return data like it does in the browser.

**Comment by shashank-reddy-nr** [comment]
Hi @sirianni ,

This issue is similar to a known problem where the response from Nerd Graph (New Relic API gateway) varies based on the query used. Specifically, when using certain queries ex: when you use FACET and TIMESERIES in same query, the otherResult and totalResult values are returned as lists, while other queries return these values as objects.

To support both data types, we would need to restructure the datatype to an interface, which is a significant change given the fragility of the newrelic-client-go package, especially considering its use cases in the other repos. Therefore, we won't be able to support queries with FACET and TIMESERIES at once from CLI, this can be only queried from UI.

### When we use FACET and TIMESERIES the nerdgraph response:
<img width="365" alt="image" src="https://github.com/user-attachments/assets/c0cec800-af19-4fb5-862c-e5b57430046b">


### When we use just FACET the nerdgraph response:
<img width="366" alt="image" src="https://github.com/user-attachments/assets/d65df10d-0271-42f5-8148-b1dab8322ef9">
